apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: kubeappsops
build:
  artifacts:
  - image: docker.io/lchdzh/kubeappsops
    docker:
      dockerfile: Dockerfile
  tagPolicy:
      envTemplate:
        template: v0.2
deploy:
  kubectl:
    defaultNamespace: kubeappsops
    manifests:
    - manifests/kubeops-config.yaml
    - manifests/kubeops-deployment.yaml
    - manifests/kubeops-rbac.yaml
    - manifests/kubeops-service.yaml
    - manifests/kubeops-serviceaccount.yaml
