---
# Source: kubeapps/templates/kubeops-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubeappsops
  labels:
    app: kubeappsops
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kubeappsops
